In [5]:
import tensorflow as tf;

In [4]:
tf.__version__

'2.10.0'

In [12]:
#check gpu availability..
a = tf.test.is_gpu_available();
a

False

In [11]:
#Create integer constant
a = tf.constant(10);
a

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [13]:
#Create float constant
b = tf.constant(10.34);
b

<tf.Tensor: shape=(), dtype=float32, numpy=10.34>

In [14]:
#Create string constant
c = tf.constant("abdul kadir khan");
c

<tf.Tensor: shape=(), dtype=string, numpy=b'abdul kadir khan'>

In [16]:
#Create boolean constant
d = tf.constant(True);
d

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
#create constant numpy array/list/tuple
# import numpy as np;

In [22]:
import numpy as np;
np_array = tf.constant(np.array([1,2,3,4]));
np_array

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [11]:
#create 1D constant
c_1d = tf.constant([10,20,30,40,50]);
c_1d

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([10, 20, 30, 40, 50])>

In [10]:
#create 2D constant row,columns
c_2d = tf.constant([[10,20,100],[30,40,50]]);
c_2d

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 10,  20, 100],
       [ 30,  40,  50]])>

In [35]:
#getting the actual value of the constant..
c_2d = tf.constant([[10,20,100],[30,40,50]],shape=(2,3),dtype="float32");
c_2d

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 10.,  20., 100.],
       [ 30.,  40.,  50.]], dtype=float32)>

In [7]:
#create N-D constant
c_Nd = tf.constant([[10,20],[30,50],[98,12]]);
c_Nd
# Type of Constant
type(c_Nd);

In [16]:
# Shape of Constant
c_Nd.shape
c_2d.shape

TensorShape([2, 3])

In [25]:
# Access constant value
v = c_1d.numpy();
v


array([10, 20, 30, 40, 50])

In [24]:
v1 = c_2d.numpy()[1];
v1

array([30, 40, 50])

In [26]:
# constant dtype
v2 = c_2d.dtype;
v2

tf.int32